name: CI Pipeline

on:
  push:
    branches: ['**']
  pull_request:
    branches: [main]

jobs:
  ci:
    name: Continuous Integration
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --no-audit --prefer-offline --no-optional

      - name: Verify architecture
        run: |
          echo "Node.js version: $(node --version)"
          echo "Platform: $(node -p process.platform)"
          echo "Arch: $(node -p process.arch)"

      - name: Verify installation
        run: |
          echo "Node.js version: $(node --version)"
          echo "Platform: $(node -p process.platform)"
          echo "Arch: $(node -p process.arch)"
          ls -la node_modules/.bin/ | grep -E "(swc|next)" || true

      - name: Debug jest setup file
        run: |
          echo "Checking for jest.setup files..."
          ls -la jest.setup* || echo "No jest.setup files found"
          pwd
          echo "Contents of working directory:"
          ls -la

      - name: Type checking
        run: npm run type-check

      - name: Linting
        run: npm run lint

      - name: Format check
        run: npx prettier --check .

      - name: Unit tests with coverage
        run: npm test -- --coverage --watchAll=false --maxWorkers=2 --no-cache
        env:
          CI: true
          NODE_ENV: test
          JEST_WORKER_ID: 1

      - name: Build application
        run: npm run build
        env:
          NEXT_TELEMETRY_DISABLED: '1'
