name: CI Pipeline

on:
  push:
    branches: ['**']
  pull_request:
    branches: [main]

jobs:
  ci:
    name: Continuous Integration
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --no-audit --prefer-offline

      - name: Install SWC binaries explicitly
        run: |
          npm install @swc/core-linux-x64-gnu@latest --no-save || true
          npm install @swc/core-linux-x64-musl@latest --no-save || true
          npm install @next/swc-linux-x64-gnu@latest --no-save || true
          npm install @next/swc-linux-x64-musl@latest --no-save || true

      - name: Verify installation
        run: |
          echo "Node.js version: $(node --version)"
          echo "Platform: $(node -p process.platform)"
          echo "Arch: $(node -p process.arch)"
          ls -la node_modules/.bin/ | grep -E "(swc|next)" || true

      - name: Type checking
        run: npm run type-check

      - name: Linting
        run: npm run lint

      - name: Format check
        run: npx prettier --check .

      - name: Unit tests with coverage
        run: npm test -- --coverage --watchAll=false --maxWorkers=2
        env:
          CI: true
          NODE_ENV: test

      - name: Build application
        run: npm run build
        env:
          NODE_OPTIONS: '--no-experimental-fetch'
          NEXT_TELEMETRY_DISABLED: '1'
